flir_multicam:
  ros__parameters:
    cameras:
      - name: "camera_center"
        serial: "25415248"
        namespace: "camera_center"
        frame_id: "camera_center_optical_frame"
        hardware_trigger_role: "none"
        ptp_action_role: "sender"
        force_ip_address: "192.168.1.1"
        force_ip_subnet_mask: "255.255.255.0"
        force_ip_gateway: "0.0.0.0"
        mac_address: "2CDDA383CE50"
      - name: "camera_front_right"
        serial: "26076473"
        namespace: "camera_front_right"
        frame_id: "camera_front_right_optical_frame"
        hardware_trigger_role: "none"
        ptp_action_role: "receiver"
        force_ip_address: "192.168.1.2"
        force_ip_subnet_mask: "255.255.255.0"
        force_ip_gateway: "0.0.0.0"
        mac_address: "2CDDA38DE539"
      - name: "camera_front_left"
        serial: "26076477"
        namespace: "camera_front_left"
        frame_id: "camera_front_left_optical_frame"
        hardware_trigger_role: "none"
        ptp_action_role: "receiver"
        force_ip_address: "192.168.1.3"
        force_ip_subnet_mask: "255.255.255.0"
        force_ip_gateway: "0.0.0.0"
        mac_address: "2CDDA38DE53D"
      - name: "camera_side_right_1"
        serial: "25415254"
        namespace: "camera_side_right_1"
        frame_id: "camera_side_right_1_optical_frame"
        hardware_trigger_role: "none"
        ptp_action_role: "receiver"
        force_ip_address: "192.168.1.4"
        force_ip_subnet_mask: "255.255.255.0"
        force_ip_gateway: "0.0.0.0"
        mac_address: "2CDDA383CE56"
      - name: "camera_side_right_2"
        serial: "26076472"
        namespace: "camera_side_right_2"
        frame_id: "camera_side_right_2_optical_frame"
        hardware_trigger_role: "none"
        ptp_action_role: "receiver"
        force_ip_address: "192.168.1.5"
        force_ip_subnet_mask: "255.255.255.0"
        force_ip_gateway: "0.0.0.0"
        mac_address: "2CDDA38DE538"
      - name: "camera_side_left_1"
        serial: "25415250"
        namespace: "camera_side_left_1"
        frame_id: "camera_side_left_1_optical_frame"
        hardware_trigger_role: "none"
        ptp_action_role: "receiver"
        force_ip_address: "192.168.1.6"
        force_ip_subnet_mask: "255.255.255.0"
        force_ip_gateway: "0.0.0.0"
        mac_address: "2CDDA383CE52"
      - name: "camera_side_left_2"
        serial: "25415249"
        namespace: "camera_side_left_2"
        frame_id: "camera_side_left_2_optical_frame"
        hardware_trigger_role: "none"
        ptp_action_role: "receiver"
        force_ip_address: "192.168.1.7"
        force_ip_subnet_mask: "255.255.255.0"
        force_ip_gateway: "0.0.0.0"
        mac_address: "2CDDA383CE51"
      - name: "camera_rear"
        serial: "26076003"
        namespace: "camera_rear"
        frame_id: "camera_rear_optical_frame"
        hardware_trigger_role: "none"
        ptp_action_role: "receiver"
        force_ip_address: "192.168.1.8"
        force_ip_subnet_mask: "255.255.255.0"
        force_ip_gateway: "0.0.0.0"
        mac_address: "2CDDA38DE363"
